version: '3'
services:
  pyos:
    depends_on:
      - memcached
      - mongodb
    image: abcdesktopio/oc.pyos:${TAG:-latest}
    networks:
      - netback
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  speedtest:
    image: abcdesktopio/oc.speedtest:${TAG:-latest}
    networks:
      - netuser
  
  nginx:
    depends_on:
      - memcached
      - pyos
    image: abcdesktopio/oc.nginx:${TAG:-latest}
    ports:
      - 80:80
      - 443:443
    networks:
      - netuser
      - netback
  
  memcached:
    image: memcached
    networks:
      - netback
  
  mongodb:
    image: mongo:4.4
    networks:
      - netback

networks:
  netuser:
    driver: bridge
  netback:
    internal: true
