apiVersion: v1
kind: ConfigMap
metadata:
  name: abcdesktop-passwd-templatefile
  namespace: abcdesktop
data:
  passwd: |
    root:x:0:0:root:/root:/bin/bash
    daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
    bin:x:2:2:bin:/bin:/usr/sbin/nologin
    sys:x:3:3:sys:/dev:/usr/sbin/nologin
    sync:x:4:65534:sync:/bin:/bin/sync
    games:x:5:60:games:/usr/games:/usr/sbin/nologin
    man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
    lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
    mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
    news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
    uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
    proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
    www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
    backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
    list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
    irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
    gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
    nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
    _apt:x:100:65534::/nonexistent:/usr/sbin/nologin
    messagebus:x:101:102::/nonexistent:/usr/sbin/nologin
    pulse:x:102:104:PulseAudio daemon,,,:/var/run/pulse:/usr/sbin/nologin
    polkitd:x:999:999:User for polkitd:/:/usr/sbin/nologin
    sshd:x:4095:65534::/run/sshd:/usr/sbin/nologin
    {{ uid }}:x:{{ uidNumber }}:{{ gidNumber }}:{{ gecos }}:{{ homeDirectory }}:{{ loginShell }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: abcdesktop-group-templatefile
  namespace: abcdesktop
data:
  group: |
    root:x:0:
    daemon:x:1:
    bin:x:2:
    sys:x:3:
    adm:x:4:
    tty:x:5:
    disk:x:6:
    lp:x:7:
    mail:x:8:
    news:x:9:
    uucp:x:10:
    man:x:12:
    proxy:x:13:
    kmem:x:15:
    dialout:x:20:
    fax:x:21:
    voice:x:22:
    cdrom:x:24:
    floppy:x:25:
    tape:x:26:
    sudo:x:27:{{ uid }}
    audio:x:29:pulse
    dip:x:30:
    www-data:x:33:
    backup:x:34:
    operator:x:37:
    list:x:38:
    irc:x:39:
    src:x:40:
    gnats:x:41:
    shadow:x:42:
    utmp:x:43:
    video:x:44:
    sasl:x:45:
    plugdev:x:46:
    staff:x:50:
    games:x:60:
    users:x:100:
    nogroup:x:65534:
    lpadmin:x:101:root,{{ uid }}
    messagebus:x:102:
    ssl-cert:x:103:
    pulse:x:104:
    pulse-access:x:105:
    plocate:x:106:
    input:x:107:
    sgx:x:108:
    kvm:x:109:
    render:x:110:
    _ssh:x:111:
    polkitd:x:999:
    nogroup:x:65534:
    ssh:x:4095:
    {{ gid }}:x:{{ gidNumber }}:{{ uid }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: abcdesktop-shadow-templatefile
  namespace: abcdesktop
data:
  shadow: |
    root:*:19020:0:99999:7:::
    daemon:*:19020:0:99999:7:::
    bin:*:19020:0:99999:7:::
    sys:*:19020:0:99999:7:::
    sync:*:19020:0:99999:7:::
    games:*:19020:0:99999:7:::
    man:*:19020:0:99999:7:::
    lp:*:19020:0:99999:7:::
    mail:*:19020:0:99999:7:::
    news:*:19020:0:99999:7:::
    uucp:*:19020:0:99999:7:::
    proxy:*:19020:0:99999:7:::
    www-data:*:19020:0:99999:7:::
    backup:*:19020:0:99999:7:::
    list:*:19020:0:99999:7:::
    irc:*:19020:0:99999:7:::
    gnats:*:19020:0:99999:7:::
    nobody:*:19020:0:99999:7:::
    _apt:*:19020:0:99999:7:::
    sshd:*:17987:0:99999:7:::
    messagebus:*:19040:0:99999:7:::
    pulse:*:19041:0:99999:7:::
    polkitd:!*:20157::::::
    {{ uid }}:{{ sha512 }}:19080:0:99999:7:::
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: abcdesktop-gshadow-templatefile
  namespace: abcdesktop
data:
  gshadow: |
    root:*::
    daemon:*::
    bin:*::
    sys:*::
    adm:*::
    tty:*::
    disk:*::
    lp:*::
    mail:*::
    news:*::
    uucp:*::
    man:*::
    proxy:*::
    kmem:*::
    dialout:*::
    fax:*::
    voice:*::
    cdrom:*::
    floppy:*::
    tape:*::
    sudo:*::{{ uid }}
    audio:*::
    dip:*::
    www-data:*::
    backup:*::
    operator:*::
    list:*::
    irc:*::
    src:*::
    gnats:*::
    shadow:*::
    utmp:*::
    video:*::
    sasl:*::
    plugdev:*::
    staff:*::
    games:*::
    users:*::
    nogroup:*::
    lpadmin:!::root,{{ uid }}
    messagebus:!::
    ssl-cert:!::
    pulse:x:!::
    pulse-access:!::
    plocate:!::
    input:!::
    sgx:!::
    kvm:!::
    render:!::
    polkitd:!::
    {{ gid }}:!::{{ uid }}
