apiVersion: batch/v1
kind: Job 
metadata:
  namespace: abcdesktop
  name: jobpostmantest
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: postmantest
        image: abcdesktopio/oc.postmantest:main
