apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  namespace: abcdesktop
  name: macvlan-conf-eth2
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth2",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.9.1.0/24",
        "rangeStart": "10.9.1.10",
        "rangeEnd": "10.9.1.99",
        "gateway": "10.9.1.100"
      }
    }'
