apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  namespace: abcdesktop
  name: macvlan-conf-eth3
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth3",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.29.0/24",
        "rangeStart": "192.168.29.10",
        "rangeEnd": "192.168.29.99",
        "gateway": "192.168.29.100"
      }
    }'
