apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-gce
  namespace: abcdesktop
spec:
  acme:
    email: XXXXXXXXXXXXXXXX   # ENTER A VALID EMAIL ADDRESS HERE
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-gce-private-key
    solvers:
    - http01:
        ingress:
          name: ingress-abcdesktop
