apiVersion: batch/v1
kind: CronJob
metadata:
  name: abcdesktop-cleaner
spec:
  schedule: "*/15 * * * *"
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      activeDeadlineSeconds: 60
      backoffLimit: 0
      template:
        metadata:
          labels:
            name: abcdesktop-cleaner
            netpol/pyos: 'true'
            netpol/dns: 'true'
        spec:
          containers:
          - name: abcdesktop-cleaner
            image: busybox
            args:
            - /bin/sh
            - -c
            - > 
              wget -q -t 3 -O- 
              --header="X-API-KEY: demoabcdesktop"  
              "http://${PYOS_ADDR}:${PYOS_PORT}/API/manager/garbagecollector?expirein=${EXPIREIN}&force=${FORCE}"
            env:
            - name: PYOS_ADDR
              value: 'pyos.abcdesktop.svc.cluster.local'
            - name: PYOS_PORT
              value: '8000'
            - name: EXPIREIN
              value: '900'
            - name: FORCE
              value: 'false'
          restartPolicy: OnFailure
          dnsPolicy: ClusterFirst
